[package]
name = "darya-website"
authors = ["Felipe S.C. Lorentz <113468900+SCLorentz@users.noreply.github.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]